"""Export the API contract for hand-off: ``docs/api/openapi.json`` (the machine-readable
spec — feed it to a client generator) and ``docs/api/README.md`` (one line per endpoint, plus
the request/response schemas, flat enough to read without the codebase). Regenerate with
``lazy api export`` whenever routes change; a test keeps the committed copy current."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from fastapi import FastAPI

METHOD_ORDER = ("get", "post", "put", "delete", "patch")


def openapi_dict(app: FastAPI) -> dict[str, Any]:
    return app.openapi()


def _schema_name(ref: dict[str, Any] | None) -> str | None:
    if not ref:
        return None
    if "$ref" in ref:
        return ref["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in ref:  # Optional[Model] body → anyOf [Model, null]
        names = [n for n in (_schema_name(o) for o in ref["anyOf"]) if n and n != "null"]
        return (names[0] + "?") if names else None
    if ref.get("type") == "array" and "$ref" in ref.get("items", {}):
        return ref["items"]["$ref"].rsplit("/", 1)[-1] + "[]"
    return ref.get("type")


def _type_str(prop: dict[str, Any]) -> str:
    if "$ref" in prop:
        return prop["$ref"].rsplit("/", 1)[-1]
    if "anyOf" in prop:
        return " | ".join(_type_str(p) for p in prop["anyOf"])
    t = prop.get("type", "any")
    if t == "array":
        return f"{_type_str(prop.get('items', {}))}[]"
    if t == "object" and "additionalProperties" in prop:
        ap = prop["additionalProperties"]
        return f"dict[str, {_type_str(ap) if isinstance(ap, dict) else 'any'}]"
    return t


def to_markdown(spec: dict[str, Any]) -> str:
    info = spec.get("info", {})
    out = [
        f"# {info.get('title', 'API')} {info.get('version', '')} — endpoint reference",
        "",
        "Generated by `lazy api export` from the live FastAPI app; the authoritative",
        "machine-readable contract is `openapi.json` next to this file (also served at",
        "`/openapi.json`, interactive at `/docs`). All responses are JSON unless marked HTML.",
        "No auth (the draft-night host is reached over Tailscale). Times are ISO-8601 UTC.",
        "",
        "## Endpoints",
        "",
        "| Method | Path | Purpose | Query / body | Returns |",
        "|---|---|---|---|---|",
    ]
    used: list[str] = []
    for path, ops in spec.get("paths", {}).items():
        for method in METHOD_ORDER:
            op = ops.get(method)
            if not op:
                continue
            doc = (op.get("description") or op.get("summary") or "").strip()
            doc = " ".join(doc.split())
            params = []
            for p in op.get("parameters", []):
                if p.get("in") == "path":
                    continue
                req = "" if p.get("required") else "?"
                params.append(f"`{p['name']}{req}`")
            body = op.get("requestBody", {}).get("content", {}).get("application/json", {})
            body_name = _schema_name(body.get("schema"))
            if body_name:
                params.append(f"body `{body_name}`")
                used.append(body_name.rstrip("?"))
            resp = op.get("responses", {}).get("200", {}).get("content", {})
            if "text/html" in resp:
                ret = "HTML"
            else:
                ret = _schema_name(resp.get("application/json", {}).get("schema")) or "JSON"
                if ret.rstrip("[]") in spec.get("components", {}).get("schemas", {}):
                    used.append(ret.rstrip("[]"))
                    ret = f"`{ret}`"
            cells = (method.upper(), f"`{path}`", doc or "—", ", ".join(params) or "—", ret)
            out.append("| " + " | ".join(cells) + " |")
    schemas = spec.get("components", {}).get("schemas", {})
    out += ["", "## Schemas", ""]
    seen: set[str] = set()
    queue = [n for n in used if n in schemas]
    while queue:
        name = queue.pop(0)
        if name in seen:
            continue
        seen.add(name)
        sch = schemas[name]
        out.append(f"### {name}")
        if sch.get("description"):
            out.append("")
            out.append(" ".join(sch["description"].split()))
        out += ["", "| Field | Type | Required | Notes |", "|---|---|---|---|"]
        required = set(sch.get("required", []))
        for fname, prop in sch.get("properties", {}).items():
            t = _type_str(prop)
            for ref in _refs(prop):
                if ref in schemas and ref not in seen:
                    queue.append(ref)
            notes = []
            if "default" in prop:
                notes.append(f"default `{json.dumps(prop['default'])}`")
            for k in ("minimum", "maximum", "exclusiveMinimum", "exclusiveMaximum", "pattern"):
                if k in prop:
                    notes.append(f"{k} `{prop[k]}`")
            if prop.get("description"):
                notes.append(" ".join(prop["description"].split()))
            out.append(
                f"| `{fname}` | {t} | {'yes' if fname in required else ''} | {'; '.join(notes)} |"
            )
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _refs(prop: dict[str, Any]) -> list[str]:
    refs = []
    if "$ref" in prop:
        refs.append(prop["$ref"].rsplit("/", 1)[-1])
    for sub in prop.get("anyOf", []):
        refs += _refs(sub)
    if "items" in prop:
        refs += _refs(prop["items"])
    ap = prop.get("additionalProperties")
    if isinstance(ap, dict):
        refs += _refs(ap)
    return refs


def export(app: FastAPI, out_dir: Path) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    spec = openapi_dict(app)
    json_path = out_dir / "openapi.json"
    md_path = out_dir / "README.md"
    json_path.write_text(json.dumps(spec, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    md_path.write_text(to_markdown(spec), encoding="utf-8")
    return json_path, md_path


__all__ = ["export", "openapi_dict", "to_markdown"]
